---
- name: role rancher
  hosts: Rancher
  remote_user: root
  tasks:

          - name: pull et run rancher/server container
            beycome: yes
            docker_container:
               name: "rancher"
               image: rancher/server:latest
               state: started
               restart_policy: always
               ports:
                 - "8080:8080"

          - name: Wait for the Rancher server to start
            beycome: yes
            command: docker logs rancher
            register: rancher_logs
            until: rancher_logs.stdout.find("Listening on") != -1
            retries: 30
            delay: 10
